# Generated by Django 4.1.1 on 2022-09-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=' ', max_length=100, unique=True)),
                ('password', models.CharField(default=' ', max_length=100)),
                ('first_name', models.CharField(blank=True, default=' ', max_length=100)),
                ('last_name', models.CharField(blank=True, default=' ', max_length=100)),
                ('phonenumber', models.CharField(max_length=15, unique=True)),
                ('isdoctor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
