# Generated by Django 4.1.1 on 2022-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discraption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
